### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by krzysiekpiasecki** [krzysiekpiasecki/burze.dzis.net#1]
# Milestone 1.0

__Must have__
- [ ] Reqest for ```lista_miejscowosci```
- [ ] Test
- [ ] Docs
- [ ] CI -> travis-ci.org?
- [ ] Error handler

__Could have__
- [ ] Caching strategy
- [ ] APIKey Resolving Strategy (env, ...) -> type APIKeyResolv interface
